### ISSUE TITLE
Tree Multiselect in Bower Registry?

### ISSUE THREAD

**Issue by MiguelSR** [patosai/tree-multiselect#17]
Hello.

Have you considered about registring Tree Multiselect in Bower Registry? It would make the plugin easier to install.

More info here:

https://bower.io/docs/creating-packages/

Thanks!
Miguel.

**Comment by patosai** [comment]
Sure I'll look into it.

**Comment by patosai** [comment]
Sure I'll look into it.

**Comment by patosai** [comment]
Looks like it's registered in the bower registry now. Try it out and let me know if it works.

**Comment by MiguelSR** [comment]
Yes!!! Thank you very much, it's working now :)
