### ISSUE TITLE
How to check the parent node is selected?

### ISSUE THREAD

**Issue by Rameezmhmd** [patosai/tree-multiselect#18]
If I have tree like this,

- Parent 1 (value:parent1)
    - Child 1 (value:child1)
    - Child 2(value:child2)
    - Child 3 (value:child3)
- Parent 2
    - Child 4
    - Child 5
    - Child 6

As per your code, when I click Parent 1, whole child 1, child 2 and child 3 will be selected. Thats good. But. How can I check whether is selected parent node or child nodes? Suppose I click Child2, value selected is displaying as child2, and if Parent 1 is selected, values selected are displaying as child1, child2 and child3. instead of displaying all 3, is there any possiblity display only value = parent1 when click Parent1 ?

**Comment by patosai** [comment]
You can't do that right now.

Originally the idea of the plugin was to get some sort of ordering for the flat select element. I suppose you could also do that on the server side.

This seems like it could be useful.

**Comment by Rameezmhmd** [comment]
Ok. Can you tell me how to get selected option using code? I couldnt find it using allSelectedItems
In above example, when I click child 2, how can I check child2 is clicked using code (jquery)?

**Comment by patosai** [comment]
Just go to your select.
